### ISSUE TITLE
GitHub Enterprise integration broken

### ISSUE THREAD

**Issue by chringwer** [gocd-contrib/github-oauth-authorization-plugin#11]
Although the API space in github enterprise is `/api/v3` which needs to be present in the configured github URL, for the login flow the `/api/v3` part needs to be omitted.

**Comment by vivekdubey** [comment]
@chringwer did you find any work around for authenticating GoCD with Github enterprise?

**Comment by chringwer** [comment]
@vivekdubey No, I had to patch the plugin. Did not find the time for a proper and robust implementation, but this should make it work: https://github.com/chringwer/github-oauth-authorization-plugin/commit/5f18971b8affa42a45014594b6b542e0c04eafa8

**Comment by vivekdubey** [comment]
Thanks @chringwer! You are a champion :)

**Comment by arvindsv** [comment]
Can someone on this thread verify whether https://github.com/gocd-contrib/github-oauth-authorization-plugin/pull/60 works? It's a smaller change than the commit mentioned here by @chringwer and I'm thinking it's going to be easier for one of you to take a look, since you probably have it set up already.
